require: rubocop-rails

AllCops:
  NewCops: enable

Style/Documentation:
  Enabled: false

Rails/FilePath:
  EnforcedStyle: arguments

Rails:
  Enabled: true

Style/FrozenStringLiteralComment:
  Enabled: false

Layout/LineLength:
  Max: 250

Metrics/MethodLength:
  Max: 30

Metrics/BlockLength:
  Exclude:
    - 'Rakefile'
    - '**/*.rake'
    - 'test/**/*.rb'
